name: Build/release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [14]
        # os: [macos-latest, ubuntu-latest, windows-latest]
        # os: [ubuntu-latest, macos-10.15, windows-2019]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            friendlyName: Ubuntu
        #   - os: macos-10.15
        #     friendlyName: macOS
        #   - os: windows-2019
        #     friendlyName: Windows
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Run Install
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install

      - name: Setup Xvfb
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Install display server dependencies
          # Install core libraries for chromium driver
          sudo apt install -y xvfb libxtst6 libxss1 libgtk2.0-0 libnss3 libasound2 libgconf-2-4
          export {no_proxy,NO_PROXY}="127.0.0.1,localhost"
          export DISPLAY=:99.0
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3

      - name: Run Coverage
        run: yarn test:unit

      - name: Push to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Cypress
        run: yarn test:e2e -- --headless

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          use_vue_cli: true
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
