name: Build/release

on:
  push:
    branches:
      - "*"

jobs:
  test-unit:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [14.13.1]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            friendlyName: Unit Test - Ubuntu
          - os: macos-latest
            friendlyName: Unit Test - MacOS
          - os: windows-latest
            friendlyName: Unit Test - Windows
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run Install
        run: |
          npm install

      # - name: Setup Xvfb
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     # Install display server dependencies
      #     # Install core libraries for chromium driver
      #     sudo apt install -y xvfb libxtst6 libxss1 libgtk2.0-0 libnss3 libasound2 libgconf-2-4
      #     export {no_proxy,NO_PROXY}="127.0.0.1,localhost"
      #     export DISPLAY=:99.0
      #     Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      #     sleep 3

      - name: Run Unit Test with
        run: npm run test:unit

      # - name: Push to Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

  test-functional:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [14.13.1]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            friendlyName: Functional Test - Ubuntu

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run Cypress using Docker
        run: |
          docker compose up --abort-on-container-exit --quiet-pull --renew-anon-volumes

  release:
    if: "!contains(github.event.head_commit.message, 'skip ci') && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')"
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [14.13.1]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            friendlyName: Release - Ubuntu
          - os: macos-latest
            friendlyName: Release - MacOS
          - os: windows-latest
            friendlyName: Release - Windows
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run Install
        run: |
          npm install

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: "app:build"
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
